spring.application.name=monolito-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/tcc_pedidos
spring.datasource.username=tcc
spring.datasource.password=tcc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

pagamento.mock.limite-aprovacao=10000